/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import clases.Password;
import javax.swing.JOptionPane;
/**
 *
 * @author Jesus
 */
public class Principal extends javax.swing.JFrame {
int longitud;
        String contrasena;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        txtLongitud.setText("8");
        txtLongitud.requestFocusInWindow();
        txtLongitud.selectAll();
        cmdCambiar.setEnabled(false);
            cmdSeguridad.setEnabled(false);
            cmdVer.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cmdListo = new javax.swing.JButton();
        cmdCambiar = new javax.swing.JButton();
        cmdSeguridad = new javax.swing.JButton();
        cmdVer = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtLongitud = new javax.swing.JTextField();
        txtContra = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Txt", 0, 36)); // NOI18N
        jLabel1.setText("Contraseña");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel3.setText("Ingresar contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("MS Reference Sans Serif", 0, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdListo.setText("Listo");
        cmdListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdListoActionPerformed(evt);
            }
        });
        jPanel2.add(cmdListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 70, -1));

        cmdCambiar.setText("Cambiar Contraseña");
        jPanel2.add(cmdCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        cmdSeguridad.setText("Ver seguridad");
        jPanel2.add(cmdSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        cmdVer.setText("Mostrar");
        cmdVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVerActionPerformed(evt);
            }
        });
        jPanel2.add(cmdVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 200, 210));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane2.setViewportView(txtArea);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 220, 100));

        jLabel2.setText("Longitud");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));
        jPanel1.add(txtLongitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 60, -1));
        jPanel1.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdListoActionPerformed
       Password p, p1;
        Password pass2;
            int longitud = 8;
            String pass;
            pass = txtContra.getText();
            pass2 = new Password(longitud, pass);
            longitud = Integer.parseInt(txtLongitud.getText());
            pass2.setLongitud(longitud);
            
           if(txtLongitud.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite la Longitud", "error", JOptionPane.ERROR_MESSAGE);
            txtLongitud.requestFocusInWindow();
    }else  if (txtContra.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite Contraseña", "error", JOptionPane.ERROR_MESSAGE);
            txtContra.requestFocusInWindow();
        }else if (longitud != pass.length()) {
                JOptionPane.showMessageDialog(this, "La contraseña no coincide con la longitud", "ERROR", JOptionPane.ERROR_MESSAGE); 
        }else {
            contrasena = txtContra.getText();
            longitud = contrasena.length();
            
            p = new Password(longitud, contrasena);
            JOptionPane.showMessageDialog(this, "Contraseña guardada");
            
            cmdCambiar.setEnabled(true);
            cmdSeguridad.setEnabled(true);
            cmdVer.setEnabled(true);
            cmdBorrar.setEnabled(true);
            cmdListo.setEnabled(false);
            txtContra.setEditable(false);
        }
    }//GEN-LAST:event_cmdListoActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
       txtLongitud.setText("8");
        txtContra.setText("");
        txtArea.setText("");
        cmdListo.setEnabled(true);
        cmdCambiar.setEnabled(false);
        cmdSeguridad.setEnabled(false);
        cmdVer.setEnabled(false);
        cmdBorrar.setEnabled(false);
        txtContra.setEditable(true);
        txtLongitud.requestFocusInWindow();
        txtLongitud.selectAll();
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void cmdVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVerActionPerformed
       Password p, c;

        contrasena = txtContra.getText();
        longitud = contrasena.length();
        p = new Password(longitud, contrasena);
        c = p.ver();
        txtArea.setText("Su contraseña actual es: " + c.getContrasenia()+ "\n" + " longitud de su contraseña es: " + c.getLongitud());
    }//GEN-LAST:event_cmdVerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCambiar;
    private javax.swing.JButton cmdListo;
    private javax.swing.JButton cmdSeguridad;
    private javax.swing.JButton cmdVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtLongitud;
    // End of variables declaration//GEN-END:variables
}
